//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PaymentGateway.Infrastructure.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ValidationMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ValidationMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PaymentGateway.Infrastructure.Resources.ValidationMessages", typeof(ValidationMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount must be greater than 0..
        /// </summary>
        internal static string AmountPositive {
            get {
                return ResourceManager.GetString("AmountPositive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Card number must be between 14-19 characters long..
        /// </summary>
        internal static string CardNumberLength {
            get {
                return ResourceManager.GetString("CardNumberLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Card number must only contain numeric characters..
        /// </summary>
        internal static string CardNumberNumericOnly {
            get {
                return ResourceManager.GetString("CardNumberNumericOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Card number is required..
        /// </summary>
        internal static string CardNumberRequired {
            get {
                return ResourceManager.GetString("CardNumberRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Currency must be 3 characters..
        /// </summary>
        internal static string CurrencyLength {
            get {
                return ResourceManager.GetString("CurrencyLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Currency is required..
        /// </summary>
        internal static string CurrencyRequired {
            get {
                return ResourceManager.GetString("CurrencyRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Currency must be one of: USD, EUR, GBP..
        /// </summary>
        internal static string CurrencyValid {
            get {
                return ResourceManager.GetString("CurrencyValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CVV must be 3-4 characters long..
        /// </summary>
        internal static string CvvLength {
            get {
                return ResourceManager.GetString("CvvLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CVV must only contain numeric characters..
        /// </summary>
        internal static string CvvNumericOnly {
            get {
                return ResourceManager.GetString("CvvNumericOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CVV is required..
        /// </summary>
        internal static string CvvRequired {
            get {
                return ResourceManager.GetString("CvvRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expiry date must be in the future..
        /// </summary>
        internal static string ExpiryDateFuture {
            get {
                return ResourceManager.GetString("ExpiryDateFuture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expiry month must be between 1-12..
        /// </summary>
        internal static string ExpiryMonthRange {
            get {
                return ResourceManager.GetString("ExpiryMonthRange", resourceCulture);
            }
        }
    }
}
