# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    services:
      bank_simulator:
        image: bbyars/mountebank:2.8.1
        ports:
          - 2525:2525
          - 8080:8080
        options: >-
          --name bank_simulator
          --mount type=bind,source=${{ github.workspace }}/imposters,target=/imposters
        command: --configfile /imposters/bank_simulator.ejs --allowInjection

    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x
      - name: Restore dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --no-restore --configuration Release --verbosity normal --no-restore
      - name: Test
        run: dotnet test --no-build --verbosity normal --configuration Release --no-restore